### ISSUE TITLE
issue with player

### ISSUE THREAD

**Issue by facybenbook** [BoraxKid/Heist#1]
sorry for bothering you i have a problem once i open the project there is no players neither enemy any suggestion how i solve that problem please

**Comment by BoraxKid** [comment]
Did you initialize Git LFS ? If you use Github for Windows it should have asked you to do it when cloning the repo

**Comment by facybenbook** [comment]
i did everything is completed only when i open the project the players and the enemies (maybe meshes import issue ) are missing in the scene

**Comment by facybenbook** [comment]
alright i solved thx !
